spring:
  application:
    name: rococo-users
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    show-sql: false
    generate-ddl: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: flyway
    locations: classpath:db/migration/rococo-users

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    org.springframework.web: INFO
    org.springframework.ws: INFO
    org.springframework.boot.autoconfigure: INFO

---
spring:
  config:
    activate:
      on-profile: 'local'
  kafka:
    bootstrap-servers: 'localhost:${ROCOCO_KAFKA_PORT:9092}'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest
  datasource:
    url: 'jdbc:postgresql://localhost:${ROCOCO_DB_PORT:5432}/rococo-users'
    username: ${ROCOCO_DB_USER:postgres}
    password: ${ROCOCO_DB_PASSWORD:secret}

grpc:
  server:
    port: ${ROCOCO_USERS_PORT:9007}
    max-inbound-message-size: 15728640
  client:
    grpcFilesClient:
      address: 'static://localhost:${ROCOCO_FILES_PORT:9004}'
      negotiationType: PLAINTEXT
      max-inbound-message-size: 15728640

---
spring:
  config:
    activate:
      on-profile: 'docker'
  kafka:
    bootstrap-servers: 'kafka:9092'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest
  datasource:
    url: 'jdbc:postgresql://rococo-db:${ROCOCO_DB_PORT:5432}/rococo-users'
    username: ${ROCOCO_DB_USER:postgres}
    password: ${ROCOCO_DB_PASSWORD:secret}

grpc:
  server:
    port: 9007
    max-inbound-message-size: 15728640
  client:
    grpcFilesClient:
      address: 'static://files.rococo.dc:9004'
      negotiationType: PLAINTEXT
      max-inbound-message-size: 15728640

---