name: Configurable test run

on:
  workflow_dispatch:
    inputs:

      TEST_TITLE:
        description: Test Run Title. Will added in Allure Report Title
        type: string
        required: false
        default: ""

      TAG_EXPR:
        description: TAG_EXPRESSION
        type: string
        required: true
        default: debug

      TEST_ARGS:
        description: TEST_ARGS
        type: string
        required: false
        default: -vv

      BROWSER_ENABLED:
        description: Enable browser. Uncheck only for API tests
        type: boolean
        required: false
        default: true

      PAGE_LOAD_STRATEGY:
        description: BROWSER_PAGE_LOAD_STRATEGY. Param 'normal' for SCREENSHOT tests
        type: choice
        required: true
        options:
          - eager
          - normal

jobs:
  test-run:
    runs-on: ubuntu-latest
    env:
      # ---------- IMPORTANT VARS
      WORKFLOW_REPORT_ID: configurable_run
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_TOKEN_NAME: ${{ vars.GH_TOKEN_NAME }}
      GH_OWNER: ${{ github.repository_owner }}
      GH_REPO: ${{ vars.GH_REPO }}

      # ----------- BROWSER
      BROWSER_NAME: ${{ vars.BROWSER_NAME }}
      BROWSER_VERSION: ${{ vars.BROWSER_VERSION }}
      BROWSER_TIMEOUT: ${{ vars.BROWSER_TIMEOUT }}
      BROWSER_PAGE_LOAD_TIMEOUT: ${{ vars.BROWSER_PAGE_LOAD_TIMEOUT }}
      BROWSER_PAGE_LOAD_STRATEGY: ${{ vars.BROWSER_PAGE_LOAD_STRATEGY }}
      BROWSER_SIZE: ${{ vars.BROWSER_SIZE }}

      PROFILE: docker
      COMPOSE_PROFILES: test
      PREFIX: arrnel
      ARCH: amd64

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITHUB_SHA }}

      - name: Show Manual test run INFO
        run: |
          echo "TAG_EXPR = [${{ inputs.TAG_EXPR }}]"
          echo "TEST_ARGS = [${{ inputs.TEST_ARGS }}]"
          echo "BROWSER_ENABLED = [${{ inputs.BROWSER_ENABLED }}]"
          echo "BROWSER_PAGE_LOAD_STRATEGY = [${{ inputs.PAGE_LOAD_STRATEGY }}]"

      - name: Set TEST_TITLE
        uses: ./.github/actions/test-run-title
        with:
          test_title: ${{ inputs.TEST_TITLE }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build backends
        run: |
          ./gradlew jibDockerBuild -x :rococo-tests:test

      - name: Pull browser image
        if: ${{ inputs.BROWSER_ENABLED }}
        uses: ./.github/actions/pull-browser
        with:
          browser: ${{ env.BROWSER_NAME }}
          version: ${{ env.BROWSER_VERSION }}
          enable_video: ${{ env.BROWSER_REMOTE_VIDEO }}

      - name: Checkout workflow-resources branch
        uses: actions/checkout@v4
        with:
          ref: workflow-resources
          path: workflow-resources

      - name: Prepare workflow-resources directory
        run: |
          set -e
          mkdir -p workflow-resources/screenshot

      - name: Run tests
        uses: ./.github/actions/run-tests
        if: always()
        continue-on-error: true

      - name: Generate and Deploy Allure Report in GitHub Pages
        uses: ./.github/actions/generate-and-deploy-allure-report
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          subfolder: ${{ env.WORKFLOW_REPORT_ID }}
          report_name: ${{ env.TEST_TITLE }}
          allure_results_path: allure-results
          allure_history_path: allure-history
          report_branch: gh-pages
